import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/providers/ThemeProvider";
import { QuizgeekProvider } from "@/providers/QuizgeekProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "QuizGeek App",
  description: "Generated by create next app",
};
console.log("layout in reacg");
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <ClerkProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <QuizgeekProvider>
              <div className={`w-screen h-screen flex flex-col items-center`}>
                {children}
              </div>
            </QuizgeekProvider>
          </body>
        </html>
      </ClerkProvider>
    </ThemeProvider>
  );
}
