import type { Metadata } from "next";
import {
  ClerkProvider,
  SignIn,
  SignInButton,
  SignOutButton,
  SignUp,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Base } from "@/_parts/Base";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { Header } from "@/_parts/Header";
import { ContentSideBar } from "@/_parts/ContentSideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "QuizGeek App",
  description: "Generated by create next app",
};
console.log("layout in reacg");
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <ClerkProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <div
              className={`w-screen h-screen flex flex-col items-center`}
            >
              {children}
            </div>
          </body>
        </html>
      </ClerkProvider>
    </ThemeProvider>
  );
}
